# Generated by Django 4.0.4 on 2022-04-21 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='appropriate',
            field=models.CharField(choices=[('child', 'under 8'), ('teenager', '8-15'), ('adult', 'adults')], default='adult', max_length=100),
        ),
    ]
