# Generated by Django 4.0.4 on 2022-04-21 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_book_appropriate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.FileField(null=True, upload_to='static/images'),
        ),
    ]
